import { Inter } from 'next/font/google'
import './globals.scss'
import 'react-input-range/lib/css/index.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Investment Fundculator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-gray-primary">{children}</body>
    </html>
  )
}
